;
; ACTIVIDAD2-OGJE-uCONTROLADORES.asm
;
; Created: 27/08/2024 06:37:26 p. m.
; Author : Joselord
;
.org 0x0000
	jmp RESET
sei

RESET:
;INICIAMOS EL STACK POINTER
	ldi r16, high(RAMEND)			;CARGAMOS LA PARTE ALTA DEL STACK POINTER EN EL REGISTRO r16
	out SPH, r16					;PARA DESPUES COLOCARLO EN STACK POINTER HIGH
	ldi r16, low(RAMEND)			;CARGAMOS LA PARTE BAJA DEL STACK POINTER EN EL REGISTRO r16
	out SPL, r16					;PARA DESPUES COLOCARLO EN STACK POINTER LOW
;DEFINIMOS ENTRADAS, SALIDAS & ACTIVAMOS RESIST PULL-UP EN SALIDAS
	ldi r16, 0b00000010				;CONFIGURAMOS PB1 COMO SALIDA Y LAS DEMAS COMO ENTRADAS, SOLO NECESITAREMOS PB5,PB4,PB3
	out DDRB, r16					;ESCRIBIMOS EN DDRB
	ldi r16, 0b00111000				;ACTIVAMOS LAS RESISTENCIAS PULL-UP DE PB5,PB4,PB3
	out PORTB, r16					;LAS RESIST SE ACTIVAN EN LAS ENTRADAS MEDIANTE PORTB
;CONFIGURACION DEL TIMER1
	ldi r16, 0b00000001				;NO PRESCALER, TCNT1 NORMAL MODE
	sts TCCR1B, r16
.cseg
START:
    in r25, PINB					;CARGAMOS LO LEIDO DE LA ENTRADA EN R25
checkeada1:
	cpi r25, 0b0011_1000			;COMPARAMOS LA ENTRADA DE R25 CON LA OPCION 1
	brne checkeada2					;SI NO ES IGUAL, SALTA A LA SIGUIENTE COMPARACION
	call CIENkhz					;SI ES IGUAL, SALTA AL LOOP DE 100KHZ
checkeada2:
	cpi r25, 0b0011_0000			;COMPARAMOS LA ENTRADA DE R25 CON LA OPCION 2
	brne checkeada3					;SI NO ES IGUAL, SALTA A LA SIGUIENTE COMPARACION
	call CIENTOCINCUENTAkhz			;SI ES IGUAL, SALTA AL LOOP DE 150KHZ
checkeada3:
	cpi r25, 0b0010_1000			;COMPARAMOS LA ENTRADA DE R25 CON LA OPCION 3
	brne checkeada4					;SI NO ES IGUAL, SALTA A LA SIGUIENTE COMPARACION
	call DOSCIENTOSkhz				;SI ES IGUAL, SALTA AL LOOP DE 200KHZ
checkeada4:
	cpi r25, 0b0010_0000			;COMPARAMOS LA ENTRADA DE R25 CON LA OPCION 4
	brne checkeada5					;SI NO ES IGUAL, SALTA A LA SIGUIENTE COMPARACION
	call DOSCIENTOSCINCUENTAkhz		;SI ES IGUAL, SALTA AL LOOP DE 250KHZ
checkeada5:
	cpi r25, 0b0001_1000			;COMPARAMOS LA ENTRADA DE R25 CON LA OPCION 5
	brne checkeada6					;SI NO ES IGUAL, SALTA A LA SIGUIENTE COMPARACION
	call TRESCIENTOSkhz				;SI ES IGUAL, SALTA AL LOOP DE 300KHZ
checkeada6:
	cpi r25, 0b0001_0000			;COMPARAMOS LA ENTRADA DE R25 CON LA OPCION 6
	brne checkeada7					;SI NO ES IGUAL, SALTA A LA SIGUIENTE COMPARACION
	call TRESCIENTOSCINCUENTAkhz	;SI ES IGUAL, SALTA AL LOOP DE 350KHZ
checkeada7:
	cpi r25, 0b0000_1000			;COMPARAMOS LA ENTRADA DE R25 CON LA OPCION 7
	brne checkeada8					;SI NO ES IGUAL, SALTA A LA SIGUIENTE COMPARACION
	call CUATROCIENTOSkhz			;SI ES IGUAL, SALTA AL LOOP DE 400KHZ
checkeada8:						
	cpi r25, 0b0000_0000			;COMPARAMOS LA ENTRADA DE R25 CON LA OPCION 8
	brne START						;SI NO ES IGUAL, SALTA AL INICIO PARA SEGUIR EL LOOP DE COMPARACION 
	call CUATROCIENTOSCINCUENTAkhz	;SI ES IGUAL, SALTA AL LOOP DE 450KHZ
	


;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~LOOOOOOPS~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
CIENkhz:
	ldi r16,0x00				;ESCRIBIMOS 0X00 EN R16
    in r25, PINB				;COMPARAMOS LA ENTRADA PARA CUANDO CAMBIE SALIR DEL LOOP
	cpi r25, 0b0011_1000
	breq INICIO1				;SI NO SE HAN MOVIDO LOS SELECTORES, INICIA EL LOOP DEL DELAY
	ret							;SI CAMBIARON, REGRESA AL LOOP DE COMPARACION INICIAL
INICIO1:
	sts TCNT1L,r16				;PONEMOS TCNT1L EN 0
	lds r17,TCNT1L				;LEEMOS PARTE BAJA DEL CONTADOR
CICLOPOSITIVO100:
	sbi PORTB,PB1				;PONEMOS EN VALOR ALTO LA SALIDA
	inc r17						;+1 AL REGISTRO R17 EN CADA LOOP
	cpi r17,13					;COMPARAMOS CONSTANTE CON VALOR DEL CONTADOR
	brne CICLOPOSITIVO100		;SI EL TCNT1L NO ES IGUAL A LA CONSTANTE SALTA AL CICLO, SI ES IGUAL YA NO SALTA

	sts TCNT1L,r16				;PONEMOS TCNT1L EN 0, O MAS FACIL UN RESET
	lds r17,TCNT1L				;LEEMOS PARTE BAJA DEL CONTADOR

CICLONEGATIVO100:
	cbi PORTB,PB1				;PONEMOS EN VALOR LOGICO BAJO PARA APAGAR LA SALIDA
	inc r17						;+1 EN EL REGISTRO POR CADA LOOP
	cpi r17,13					;COMPARAMOS CONSTANTE CON VALOR DEL CONTADOR
	brne CICLONEGATIVO100		;SI EL TCNT1L NO ES IGUAL A LA CONSTANTE SALTA AL CICLO, SI ES IGUAL YA NO SALTA

	rjmp CIENkhz


CIENTOCINCUENTAkhz:				;BASICAMENTE ES LA MISMA ESTRUCTURA DE LOOP PARA TODOS
ldi r16,0x00					;ES POR ESO QUE LAS FRECUENCIAS NO DAN EXACTAS, SI NO 
    in r25, PINB				;VALORES APROXIMADOS
	cpi r25, 0b0011_0000		;YA QUE AL CARGAR DATOS Y DEMAS, ESTAS CONSUMEN CICLOS DE RELOJ
	breq INICIO2				;LO QUE HACE QUE EL CALCULO SEA AUN MAS IMPRECISO
	ret							;ADEMAS DE USAR EL TCNT1 EN EL MODO NORMAL
INICIO2:
	sts TCNT1L,r16				;SE QUE AUN SE PUEDE OPTIMIZAR, SOLO QUE YA FUE SUFICIENTE ASM DEL 328P
	lds r17,TCNT1L				;POR UNA SEMANA, LLEVO DESDE EL LUNES TRATANDO DE QUE QUEDE
CICLOPOSITIVO150:				;Y HASTA HOY PUDE CONSEGUIRLO, Y ESO MASOMENOS
	sbi PORTB,PB1				;NO ME CONVENCE DEL TODO, PERO FUNCIONA QUE ES LO IMPORTANTE
	inc r17
	cpi r17,8					
	brne CICLOPOSITIVO150		

	sts TCNT1L,r16				
	lds r17,TCNT1L				

CICLONEGATIVO150:
	cbi PORTB,PB1				
	inc r17
	cpi r17,8					
	brne CICLONEGATIVO150		

	rjmp CIENTOCINCUENTAkhz

DOSCIENTOSkhz:
ldi r16,0x00		
    in r25, PINB				
	cpi r25, 0b0010_1000
	breq INICIO3
	ret
INICIO3:
	sts TCNT1L,r16				
	lds r17,TCNT1L				
CICLOPOSITIVO200:
	sbi PORTB,PB1				
	inc r17
	cpi r17,7					
	brne CICLOPOSITIVO200		

	sts TCNT1L,r16				
	lds r17,TCNT1L				

CICLONEGATIVO200:
	cbi PORTB,PB1				
	inc r17
	cpi r17,6					
	brne CICLONEGATIVO200		

	rjmp DOSCIENTOSkhz

DOSCIENTOSCINCUENTAkhz:
ldi r16,0x00		
    in r25, PINB				
	cpi r25, 0b0010_0000
	breq INICIO4
	ret
INICIO4:
	sts TCNT1L,r16				
	lds r17,TCNT1L				
CICLOPOSITIVO250:
	sbi PORTB,PB1				
	inc r17
	cpi r17,5					
	brne CICLOPOSITIVO250		

	sts TCNT1L,r16				
	lds r17,TCNT1L				

CICLONEGATIVO250:
	cbi PORTB,PB1				
	inc r17
	cpi r17,5					
	brne CICLONEGATIVO250		

	rjmp DOSCIENTOSCINCUENTAkhz

TRESCIENTOSkhz:
ldi r16,0x00		
    in r25, PINB				
	cpi r25, 0b0001_1000
	breq INICIO5
	ret
INICIO5:
	sts TCNT1L,r16				
	lds r17,TCNT1L				
CICLOPOSITIVO300:
	sbi PORTB,PB1				
	inc r17
	cpi r17,5					
	brne CICLOPOSITIVO300		

	sts TCNT1L,r16				
	lds r17,TCNT1L				

CICLONEGATIVO300:
	cbi PORTB,PB1				
	inc r17
	cpi r17,4					
	brne CICLONEGATIVO300		

	rjmp TRESCIENTOSkhz

TRESCIENTOSCINCUENTAkhz:
ldi r16,0x00		
    in r25, PINB				
	cpi r25, 0b0001_0000
	breq INICIO6
	ret
INICIO6:
	sts TCNT1L,r16				
	lds r17,TCNT1L				
CICLOPOSITIVO350:
	sbi PORTB,PB1				
	inc r17
	cpi r17,5					
	brne CICLOPOSITIVO350		

	sts TCNT1L,r16				
	lds r17,TCNT1L				

CICLONEGATIVO350:
	cbi PORTB,PB1				
	inc r17
	cpi r17,3					
	brne CICLONEGATIVO350		

	rjmp TRESCIENTOSCINCUENTAkhz

CUATROCIENTOSkhz:
ldi r16,0x00		
    in r25, PINB				
	cpi r25, 0b0000_1000
	breq INICIO7
	ret
INICIO7:
	sts TCNT1L,r16				
	lds r17,TCNT1L				
CICLOPOSITIVO400:
	sbi PORTB,PB1				
	inc r17
	cpi r17,4					
	brne CICLOPOSITIVO400		

	sts TCNT1L,r16				
	lds r17,TCNT1L				

CICLONEGATIVO400:
	cbi PORTB,PB1				
	inc r17
	cpi r17,3					
	brne CICLONEGATIVO400		

	rjmp CUATROCIENTOSkhz

CUATROCIENTOSCINCUENTAkhz:
	ldi r16,0x00		
    in r25, PINB				
	cpi r25, 0b0000_0000
	breq INICIO8
	ret
INICIO8:
	sts TCNT1L,r16				
	lds r17,TCNT1L				
CICLOPOSITIVO450:
	sbi PORTB,PB1				
	inc r17
	cpi r17,3					
	brne CICLOPOSITIVO450		

	sts TCNT1L,r16				
	lds r17,TCNT1L				

CICLONEGATIVO450:
	cbi PORTB,PB1				
	inc r17
	cpi r17,3					
	brne CICLONEGATIVO450		

	rjmp CUATROCIENTOSCINCUENTAkhz




